// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.7.0.0
//      SpecFlow Generator Version:3.7.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RaaLabs.Edge.Connectors.Modbus.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EndiannessExtensionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "EndiannessExtensions.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "EndiannessExtensions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "EndiannessExtensions")))
            {
                global::RaaLabs.Edge.Connectors.Modbus.Specs.Features.EndiannessExtensionsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Converting from shorts to bytes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EndiannessExtensions")]
        public virtual void ConvertingFromShortsToBytes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Converting from shorts to bytes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "DataType",
                            "Endianness",
                            "Content"});
                table1.AddRow(new string[] {
                            "Uint32",
                            "HighByteHighWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Uint32",
                            "HighByteLowWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Uint32",
                            "LowByteHighWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Uint32",
                            "LowByteLowWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Int16",
                            "HighByteHighWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Int16",
                            "HighByteLowWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Int16",
                            "LowByteHighWord",
                            "AABB CCDD  1122 3344  9988 7766"});
                table1.AddRow(new string[] {
                            "Int16",
                            "LowByteLowWord",
                            "AABB CCDD  1122 3344  9988 7766"});
#line 4
 testRunner.Given("the following shorts", ((string)(null)), table1, "Given ");
#line hidden
#line 14
 testRunner.When("converting the shorts to bytes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Content"});
                table2.AddRow(new string[] {
                            "DDCC BBAA  4433 2211  6677 8899"});
                table2.AddRow(new string[] {
                            "BBAA DDCC  2211 4433  8899 6677"});
                table2.AddRow(new string[] {
                            "CCDD AABB  3344 1122  7766 9988"});
                table2.AddRow(new string[] {
                            "AABB CCDD  1122 3344  9988 7766"});
                table2.AddRow(new string[] {
                            "BBAA DDCC  2211 4433  8899 6677"});
                table2.AddRow(new string[] {
                            "BBAA DDCC  2211 4433  8899 6677"});
                table2.AddRow(new string[] {
                            "AABB CCDD  1122 3344  9988 7766"});
                table2.AddRow(new string[] {
                            "AABB CCDD  1122 3344  9988 7766"});
#line 15
 testRunner.Then("the shorts will be converted to the following bytes", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
