# This is a basic workflow to help you get started with Actions
name: Build docker image

on:
  release:
    types: [published]

env:
  dockerHubUserName: 'raalabs'
  dockerImageName: 'shipos/timeseries-modbus'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Get git tag
      run: echo ::set-env name=tagName::$(echo ${GITHUB_REF:10})

    - name: Log tag
      run: echo $tagName

    - name: Build docker image
      run: docker build -t $dockerImageName:$tagName --build-arg CONFIGURATION="Release" -f ./Source/Dockerfile .

    - name: Docker Login 
      run: echo ${{secrets.dockerHubPassword}} | docker login -u $dockerHubUserName --password-stdin

    - name: Push docker image
      run: docker push $dockerImageName:$tagName
